using Internal.Audit.Domain.Entities.BranchAudit;

namespace Internal.Audit.Application.Contracts.Persistent.IssueValidationDesignEffectiveNessTestDetails;

public interface IIssueValidationDesignEffectiveNessCommandRespository:IAsyncCommandRepository<IssueValidationDesignEffectiveNessTestDetail>
{
}
